apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: letter-git
  namespace: letter
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fraguinha/letter
  secretRef:
    name: git-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: letter-update-automation
  namespace: letter
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: letter-git
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./k8s
